version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-1"
    AWS_ACCOUNT_ID: "512742310782"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - cd frontend
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
      - echo AWS_REGION=$AWS_REGION
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - cd frontend
      - npm run build
      - docker build -t my-app .
      - docker tag my-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-app:latest

artifacts:
  files:
    - '**/*'
